# Generated by Django 4.2.4 on 2023-08-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='user',
        ),
        migrations.AddField(
            model_name='tokens',
            name='email',
            field=models.CharField(default='', max_length=90),
        ),
    ]
