# Generated by Django 4.2.4 on 2023-08-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_rewards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewards',
            old_name='price',
            new_name='tokens',
        ),
    ]
