# Generated by Django 4.2.4 on 2023-08-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_rename_price_rewards_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('tokens', models.IntegerField(default=0)),
            ],
        ),
    ]
