# Generated by Django 4.2.4 on 2023-08-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_redeemrewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemrewards',
            name='email',
            field=models.CharField(default='', max_length=90),
        ),
    ]
