# Generated by Django 4.2.4 on 2023-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_redeemrewards_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemrewards',
            name='hash',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='tokens',
            name='hash',
            field=models.CharField(default='', max_length=256),
        ),
    ]
